apiVersion: v1
kind: Service
metadata:
  name: bet-service
  labels:
    app: bet-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 7501
    targetPort: 7501
    protocol: TCP
  selector:
    app: bet-service
    tier: backend