deployment:
  image: omaressameldin/bet-collector-bet:1.1
  port: 7501
  nameSuffix: -dep
  podSuffix: -pod
service:
  type: ClusterIP
  port: 7501
  nameSuffix: -svc
autoscaler:
  minReplicas: 2
  maxReplicas: 10
  nameSuffix: -scaler
