deployment:
  image: omaressameldin/bet-collector-graphql:1.5
  port: 8500
  nameSuffix: -dep
  podSuffix: -pod
service:
  type: ClusterIP
  port: 8500
  nameSuffix: -svc
autoscaler:
  minReplicas: 3
  maxReplicas: 10
  nameSuffix: -scaler
