apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.ingress.path }}(/|$)(.*)
          backend:
            serviceName: {{ include "api-chart.fullname" . }}{{ .Values.service.nameSuffix }}
            servicePort: {{ .Values.service.port }}