apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8500
  selector:
    app: api
    tier: backend