apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8500
      targetPort: 8500
  externalIPs:
    - 192.168.39.69
  selector:
    app: api
    tier: backend