apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 7500
      targetPort: 7500
  selector:
    app: user-service
    tier: backend