apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bet-chart.fullname" . }}{{ .Values.deployment.nameSuffix }}
spec:
  selector:
    matchLabels:
      app: {{ include "bet-chart.fullname" . }}{{ .Values.deployment.podSuffix }}
      tier: backend
  replicas: {{ .Values.autoscaler.minReplicas }}
  template:
    metadata:
      labels:
        app: {{ include "bet-chart.fullname" . }}{{ .Values.deployment.podSuffix }}
        tier: backend
    spec:
      containers:
        - name: {{ include "bet-chart.fullname" . }}{{ .Values.deployment.podSuffix }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bet-chart.fullname" . }}{{ .Values.service.nameSuffix }}
  labels:
    app: {{ include "bet-chart.fullname" . }}{{ .Values.service.nameSuffix }}
    tier: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ include "bet-chart.fullname" . }}{{ .Values.deployment.nameSuffix }}
    tier: backend

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bet-chart.fullname" . }}{{ .Values.autoscaler.nameSuffix }}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bet-chart.name" . }}{{ .Values.deployment.nameSuffix }}
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80